### ISSUE TITLE
Problem with remote_user already containing an email

### ISSUE THREAD

**Issue by andrewbiller** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#13]
Our currently env gives the REMOTE_USER = user@domain.com

I made the extension work editing the method bellow:

`protected function getRemoteUsername()
    {
        global $wgAuthRemoteuserEnvVariable;
        global $wgAuthRemoteuserDomain;

        if (isset($_SERVER[$wgAuthRemoteuserEnvVariable])) {
            $username = $_SERVER[$wgAuthRemoteuserEnvVariable];

            if ($wgAuthRemoteuserDomain) {
                $username = str_replace("$wgAuthRemoteuserDomain\\",
                    "", $username);
                $username = str_replace("@$wgAuthRemoteuserDomain",
                    "", $username);
            }
            $username = preg_replace( '/@.*/', '', $username);
        } else {
            $username = null;
        }

        return $username;
    }`

adding the line:

>  $username = preg_replace( '/@.*/', '', $username);

So it will remove the @email.com

**Comment by wow01** [comment]
is it possible not just to delete the domain extension, but to use it as username?
I try to authenticate users from two trusted domains. So I need the domain-extesion to seperate equal usernames in different domains.

**Comment by Syavne** [comment]
I'm curious, what was the error message before you made it work? (if any). I'm unable to make it work, no errors just "Not logged in".

REMOTE_AUTH comes with user@domain.com as well in our environment and I'm thinking this might be related but, sadly, adding the line did not change anything in my case.

**Comment by andrewbiller** [comment]
No error message. Actually it's like you described: not logged in.
Since I'm using the SSO, the top bar with the user and logged user dissapears, and I can't know for sure if I was logged or not (now I know it's not). That's the problem.

Uncomment the line `$username = preg_replace( '/@.*/', '', $username);` works. User is automatically logged and user info bar appears with all links.

**Comment by wow01** [comment]
I think, I found the problem. It is not caused by this extesion, but by mediawiki itself:
[https://www.mediawiki.org/wiki/Manual:$wgInvalidUsernameCharacters/en](https://www.mediawiki.org/wiki/Manual:$wgInvalidUsernameCharacters/en)
I added following two variables into my LocalSettings.php:

```
$wgInvalidUsernameCharacters = "%:";
$wgUserrightsInterwikiDelimiter = "%";
```

Now I use SSO and get logged in with user@DOMAIN.COM

**Comment by axetroll** [comment]
I tried that, but got an error.

Something must be wrong in our server configuration:



```

[428a4e27afa0e532e8c3609a] /index.php/P%C3%A1gina_principal DBQueryError from line 1054 of /var/www/wikiditec/includes/libs/rdbms/database/Database.php: A database query error has occurred. Did you forget to run your application's database schema updater after upgrading? 
Query: INSERT INTO `ldap_domains` (domain,user_id) VALUES (NULL,'506')
Function: LdapAuthenticationPlugin::saveDomain
Error: 1048 Column 'domain' cannot be null (dbd340205.brb.com.br)


Backtrace:

#0 /var/www/wikiditec/includes/libs/rdbms/database/Database.php(912): Database->reportQueryError(string, integer, string, string, boolean)
#1 /var/www/wikiditec/includes/libs/rdbms/database/Database.php(1498): Database->query(string, string)
#2 /var/www/wikiditec/extensions/LdapAuthentication/LdapAuthenticationPlugin.php(2000): Database->insert(string, array, string)
#3 /var/www/wikiditec/extensions/LdapAuthentication/LdapAuthenticationPlugin.php(1165): LdapAuthenticationPlugin::saveDomain(User, NULL)
#4 /var/www/wikiditec/extensions/LdapAuthentication/LdapAuthenticationPlugin.php(1195): LdapAuthenticationPlugin->updateUser(User)
#5 /var/www/wikiditec/includes/auth/AuthPluginPrimaryAuthenticationProvider.php(422): LdapAuthenticationPlugin->initUser(User, boolean)
#6 [internal function]: MediaWiki\Auth\AuthPluginPrimaryAuthenticationProvider->autoCreatedAccount(User, string)
#7 /var/www/wikiditec/includes/auth/AuthManager.php(2424): call_user_func_array(array, array)
#8 /var/www/wikiditec/includes/auth/AuthManager.php(1721): MediaWiki\Auth\AuthManager->callMethodOnProviders(integer, string, array)
#9 /var/www/wikiditec/includes/Setup.php(864): MediaWiki\Auth\AuthManager->autoCreateUser(User, string, boolean)
#10 /var/www/wikiditec/includes/WebStart.php(137): require_once(string)
#11 /var/www/wikiditec/index.php(40): require(string)
#12 {main}

```

update.php didn't resolve the issue, since the error is missing the value to insert it.

**Comment by andrewbiller** [comment]
It worked, you're right. Thanks for the help.

It would be nice to have this alert in readme!
