### ISSUE TITLE
maintenance/update.php throws exception

### ISSUE THREAD

**Issue by plabong** [noris-network/mediawiki-extensions-sessionprovider-remoteuser#8]
mediawiki 1.27.1
php 7.0.14
debian testing (stretch)

With enabled extension -- wfLoadExtension( 'AuthRemoteuser' ); -- maintenance script "update.php" throws following error:
```
sudo -u www-data php maintenance/update.php
Exception encountered, of type "InvalidArgumentException"
```
I even tried to preset the user á la
`REMOTE_USER=wikiadmin`
but without succes.

**Comment by h4711** [comment]
This happens even at viewing pages on a fresh install

With enabled extension -- wfLoadExtension( 'mediawiki-extensions-sessionprovider-remoteuser' ); -- visiting the wiki homepage or other pages only shows 
  Exception encountered, of type "InvalidArgumentException" 
Disabling the extension makes the mediawiki installation work again.

**Comment by h4711** [comment]
did some kind of bisect: this also happens with the other revisions of the extension even e3b3592 so it seems to be an incompatibility with 1.27.1 that existet in the code from the beginning. or there is some undocumented configuration need, as I've been using the plugin without any configuration on an empty install

**Comment by h4711** [comment]
Additionally I tested against missing configuration and added all the configuration variables mentioned in the README, whithout any change.

I did not catch anything in the logs, as mediawiki catches the exception to display that "Exception encountered, of type "InvalidArgumentException". If you have any advise how to debug mediawiki I may help.

**Comment by fnk** [comment]
I will look into this today!

**Comment by h4711** [comment]
fnk: Andreas, did you find out any? Is there a time frame to expect further details on this?

**Comment by fnk** [comment]
We have this code working from 1.27 through to 1.28 without problems.
Did you set `$wgAuthRemoteuserEnvVariable = 'REMOTE_USER'` in `LocalSettings.php` like described in the [README](https://github.com/noris-network/mediawiki-extensions-sessionprovider-remoteuser/blob/master/README.md)?

**Comment by fnk** [comment]
Maybe there is something strange going on in your shell? Thats how we call the update from `debian/postinst` of our custom build debian package:

`su www-data --shell /bin/sh --command "php /usr/share/wiki/htdocs/maintenance/update.php --quick"`

**Comment by h4711** [comment]
We did set $wgAuthRemoteuserEnvVariable, but the environment variable mentioned there has not been set through the server.
I such cases I would expect someuseful information in the logs but not an exception.

I still have to test, if setting the environment variable makes things work...

**Comment by h4711** [comment]
setting the environment variable mentioned in $wgAuthRemoteuserEnvVariable fixes it for me. 

So documentation should make clear, that it's not only $wgAuthRemoteuserEnvVariable to be set, but also a user name MUST be provided in that set server enverionment variable.

**Comment by plabong** [comment]
`$wgAuthRemoteuserEnvVariable = 'REMOTE_USER';`  was not set!
After setting the variable, the problem is still present.

**Comment by h4711** [comment]
I've set $wgAuthRemoteuserEnvVariable and that makes Requests from the Browser work, users get identified. I can also run update.php.

But other mainanaince scripts fail due to calling functions without checking the parameter value (i.e. InvalidArgumentException)

**Not being able to do runJobs.pho this breaks Categories and other things.**

```
# php refreshLinks.php 
Refreshing redirects table.
Starting from page_id 1 of 464.
100
200
300
400
Refreshing links tables.
Starting from page_id 1 of 464.
Exception encountered, of type "InvalidArgumentException"
[1df58eee491003390b6b8d1f] [no req]   InvalidArgumentException from line 98 of /opt/mediawiki-extensions/mediawiki-extensions-sessionprovider-remoteuser/AuthRemoteuser.body.php: Invalid user name
Backtrace:
#0 /opt/mediawiki-extensions/mediawiki-extensions-sessionprovider-remoteuser/AuthRemoteuser.body.php(65): AuthRemoteuser->newSessionForRequest(NULL, FauxRequest)
#1 /usr/share/mediawiki/includes/session/SessionManager.php(479): AuthRemoteuser->provideSessionInfo(FauxRequest)
#2 /usr/share/mediawiki/includes/session/SessionManager.php(182): MediaWiki\Session\SessionManager->getSessionInfoForRequest(FauxRequest)
#3 /usr/share/mediawiki/includes/WebRequest.php(700): MediaWiki\Session\SessionManager->getSessionForRequest(FauxRequest)
#4 /usr/share/mediawiki/includes/user/User.php(1203): WebRequest->getSession()
#5 /usr/share/mediawiki/includes/user/User.php(408): User->loadFromSession()
#6 /usr/share/mediawiki/includes/user/User.php(5043): User->load()
#7 /usr/share/mediawiki/includes/user/User.php(2750): User->loadOptions()
#8 /usr/share/mediawiki/includes/context/RequestContext.php(363): User->getOption(string)
#9 /usr/share/mediawiki/includes/StubObject.php(197): RequestContext->getLanguage()
#10 /usr/share/mediawiki/includes/StubObject.php(159): StubUserLang->_newObject()
#11 /usr/share/mediawiki/includes/parser/ParserOptions.php(595): StubObject->_unstub()
#12 /usr/share/mediawiki/includes/cache/MessageCache.php(183): ParserOptions->__construct()
#13 /usr/share/mediawiki/includes/cache/MessageCache.php(1030): MessageCache->getParserOptions()
#14 /usr/share/mediawiki/includes/Message.php(1161): MessageCache->transform(string, boolean, Language, NULL)
#15 /usr/share/mediawiki/includes/Message.php(829): Message->transformText(string)
#16 /usr/share/mediawiki/includes/Message.php(892): Message->toString()
#17 /usr/share/mediawiki/includes/parser/Parser.php(537): Message->text()
#18 /usr/share/mediawiki/includes/StubObject.php(105): Parser->parse(string, Title, ParserOptions, boolean, boolean, NULL)
#19 /usr/share/mediawiki/includes/StubObject.php(129): StubObject->_call(string, array)
#20 /usr/share/mediawiki/includes/content/WikitextContent.php(331): StubObject->__call(string, array)
#21 /usr/share/mediawiki/includes/content/AbstractContent.php(497): WikitextContent->fillParserOutput(Title, NULL, ParserOptions, boolean, ParserOutput)
#22 /usr/share/mediawiki/includes/content/AbstractContent.php(230): AbstractContent->getParserOutput(Title, NULL, ParserOptions, boolean)
#23 /usr/share/mediawiki/maintenance/refreshLinks.php(240): AbstractContent->getSecondaryDataUpdates(Title)
#24 /usr/share/mediawiki/maintenance/refreshLinks.php(170): RefreshLinks::fixLinksFromArticle(integer)
#25 /usr/share/mediawiki/maintenance/refreshLinks.php(58): RefreshLinks->doRefreshLinks(integer, boolean, string, boolean, boolean)
#26 /usr/share/mediawiki/maintenance/doMaintenance.php(103): RefreshLinks->execute()
#27 /usr/share/mediawiki/maintenance/refreshLinks.php(371): require_once(string)
#28 {main}

```

**Comment by h4711** [comment]
The following fixed it for me and gives an idea what went wrong in this code

**From fixed AuthRemoteuser.body.php:**

```
    protected function newSessionForRequest($username, WebRequest $request)
    {
        $id = $this->getSessionIdFromCookie($request);

        $user = (!$username ? null : User::newFromName($username, 'usable'));
        if (!$user) {
            //throw new \InvalidArgumentException('Invalid user name');
        } else {
            $this->initUser($user, $username);
        }

        $info = new SessionInfo(SessionInfo::MAX_PRIORITY, [
            'provider' => $this,
            'id' => $id,
            'userInfo' => (!$user ? null : UserInfo::newFromUser($user, true) ),
            'persisted' => false
        ]);
        $session = $this->getManager()->getSessionFromInfo($info, $request);
        $session->persist();

        return $info;
    }

```

**Comment by plabong** [comment]
Patch from @h4711 successfully tested:
- new members correctly placed in mediwiki's users table
- maintenance scripts fully usable now
